DROP TABLE IF EXISTS USERDETAILS;
CREATE TABLE USERDETAILS
(
  id NUMBER(10) NOT NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  address VARCHAR(250),
  telephone VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);